In [1]:
import pandas as pd
print(pd.__version__)

2.3.3


In [13]:
# series的创建

s = pd.Series([1,2,3,4,5])
print(s)


pass

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64
1
a    11
b    22
c    33
dtype: int64
a    11
c    33
dtype: int64


In [ ]:

# 自定义索引
s = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'])
print(s)


In [ ]:

# 定义标签
s = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'], name='数据标签, 描述这一列的数据是什么数据')
print(s)
print(s['a'])


In [ ]:

# 通过字典dict创建Series
s2 = pd.Series({'a':11, 'b':22, 'c':33})
print(s2)


In [ ]:

# 从已有的Series中创建, index=['a', 'c']表示从s2中只读取a，c索引对应的数据
s3 = pd.Series(s2, index=['a', 'c'])
print(s3)

![img_2.png](./img/img_2.png)

In [26]:
# 基本属性
s = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'], name='数据标签, 描述这一列的数据是什么数据')
print(s.index)
print(s.values)
print(s.dtype)
print(s.dtypes)
print(s.shape)
print(s.ndim)
print(s.size)
print(s.name)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]
int64
int64
(5,)
1
5
数据标签, 描述这一列的数据是什么数据
1
1
a    1
b    2
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64
2
3


In [35]:
# 索引属性
s = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'], name='数据标签, 描述这一列的数据是什么数据')

# loc , iloc
# loc表示按显示索引，即由指定index属性的时候才能勇敢， loc -->>> location
# iloc表示按从0开始的数字索引进行访问；iloc -->>> integer location
# loc和iloc可以进行切片操作
print(s.loc['a'])
# 注意：：：loc的标签索引切片是包含条件两边的，即右侧也是闭合的
print(s.loc['a':'a'])
print(s.loc['a':'b'])
print(s.loc['a':'c'])
print()
print(s.iloc[0])
# iloc的数字切片是前闭后开的，即不包含条件右侧
print(s.iloc[0:0])
print(s.iloc[0:1])
print(s.iloc[0:2])

1
a    1
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64
a    1
b    2
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64
a    1
b    2
c    3
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64

1
Series([], Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64)
a    1
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64
a    1
b    2
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64


In [44]:
# 索引属性，索引单个数据
s = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'], name='数据标签, 描述这一列的数据是什么数据')

# at, iat
# Series.at：按「标签」取单个值（label）
# Series.iat：按「位置」取单个值（integer position）
# at访问数据比loc访问数据更快
print(s.at['b'])
# at也可以修改数据
s.at['b'] = 666
print(s.at['b'])
# 如果尝试访问一个不存在的key，会抛出错误： KeyError: 'aaa'
# print(s.at['aaa'])
print(s.iat[2])
# IndexError: index 123 is out of bounds for axis 0 with size 5
# print(s.iat[123])

# at或iat的使用场景：1、在循环里频繁访问单个元素；2、明确只取一个值

2
666
3
1
10    1
20    2
30    3
dtype: int64
1


In [54]:

# 注意⚠️⚠️⚠️：loc和at只能使用index指定的数据标签访问，而iloc和iat只能使用从0开始的数字索引访问
# 如下是经典的错误
# 数据是[1,2,3,4,5]，而使用[10,20,30,40,50]来指定数据的标签
serr = pd.Series([1,2,3,4,5], index=[10,20,30,40,50])
# 演示：loc和ta只能使用inde向指定的标签访问
print(serr.loc[10])
print(serr.loc[10:30])
print(serr.at[10])
# print(serr.at[1]) KeyError: 1
print()
# 演示：iloc和iat只能使用从0开始的数字索引访问
print(serr.iloc[0:1])
# IndexError: index 10 is out of bounds for axis 0 with size 5
# print(serr.iat[10])

1
10    1
20    2
30    3
dtype: int64
1

10    1
dtype: int64


In [67]:
# series访问数据
s = pd.Series([1,2,3,4,5,6], index=['a','b','c','d','e', 'f'])

# 直接访问
print(s[0])
print(s['a'])

# bool索引
print(s[s % 2 == 0])

# 取前5行数据
print(s.head())
print(s.head(2)) # 前两行

# 取数据后5行
print(s.tail())

pass

1
1
b    2
d    4
f    6
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
dtype: int64
b    2
c    3
d    4
e    5
f    6
dtype: int64


C:\Users\nhjcl\AppData\Local\Temp\ipykernel_16652\3654796713.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


Series常用方法
![img_3.png](./img/img_3.png)
![img_4.png](./img/img_4.png)

In [69]:

# series常用方法
s = pd.Series([1,2,3,4,5,6,7,8,9], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], name='数据标签, 描述这一列的数据是什么数据')

print(s.head())
print(s.head(2))

print(s.tail())
print(s.tail(2))


a    1
b    2
c    3
d    4
e    5
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64
a    1
b    2
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64
e    5
f    6
g    7
h    8
i    9
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64
h    8
i    9
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64


In [74]:
# 判断数据是否在series中，返回一个新的series，indexs与原series相同，而值values则为bool
print(s.isin([2]))
print(s.isin([2,3]))
print(s.isin([2,3,111]))

a    False
b     True
c    False
d    False
e    False
f    False
g    False
h    False
i    False
Name: 数据标签, 描述这一列的数据是什么数据, dtype: bool
a    False
b     True
c     True
d    False
e    False
f    False
g    False
h    False
i    False
Name: 数据标签, 描述这一列的数据是什么数据, dtype: bool
a    False
b     True
c     True
d    False
e    False
f    False
g    False
h    False
i    False
Name: 数据标签, 描述这一列的数据是什么数据, dtype: bool


In [77]:

s = pd.Series([1,2,3,4,5,6,7,8,9], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], name='数据标签, 描述这一列的数据是什么数据')
print(s.isna)
s.iat[3] = pd.NA
s.iat[7] = None
print(s.isna)





<bound method Series.isna of a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
Name: 数据标签, 描述这一列的数据是什么数据, dtype: int64>
<bound method Series.isna of a    1.0
b    2.0
c    3.0
d    NaN
e    5.0
f    6.0
g    7.0
h    NaN
i    9.0
Name: 数据标签, 描述这一列的数据是什么数据, dtype: float64>


In [80]:
s = pd.Series([6,2,5,5,5,6,8,8,9], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], name='数据标签')
print(s)
print(s.mode()) # 返回众数

print(s.describe())

a    6
b    2
c    5
d    5
e    5
f    6
g    8
h    8
i    9
Name: 数据标签, dtype: int64
0    5
Name: 数据标签, dtype: int64
count    9.00000
mean     6.00000
std      2.12132
min      2.00000
25%      5.00000
50%      6.00000
75%      8.00000
max      9.00000
Name: 数据标签, dtype: float64


In [85]:
# 各个元素出现的次数，返回一个新的series，index为就series对应values的去重后元素，values为对应出现的次数
print(s.value_counts())

数据标签
5    3
6    2
8    2
2    1
9    1
Name: count, dtype: int64


In [89]:
s.iat[3] = pd.NA
# 统计非缺失值个数
print(s.count())
print(s.size)


8
9


In [92]:
# 获取去重后的值数组，注意返回的是py的普通数组，不是pd的series
print(s.unique())

[ 6.  2.  5. nan  8.  9.]


In [95]:
# 去除重复项, 返回新的没有重复元素的数据
print(s)
print(s.drop_duplicates())

a    6.0
b    2.0
c    5.0
d    NaN
e    5.0
f    6.0
g    8.0
h    8.0
i    9.0
Name: 数据标签, dtype: float64
a    6.0
b    2.0
c    5.0
d    NaN
g    8.0
i    9.0
Name: 数据标签, dtype: float64


In [102]:
# 随机抽样
print(s.sample())
print(s.sample())
print(s.sample())

d   NaN
Name: 数据标签, dtype: float64
b    2.0
Name: 数据标签, dtype: float64
i    9.0
Name: 数据标签, dtype: float64


In [104]:
s = pd.Series([6,2,5,1,5,6,8,8,9], index=['b', 'e', 'f', 'i', 'h', 'c', 'd', 'a', 'g'], name='数据标签')

# 按索引排序
print(s.sort_index())
# 按值排序
print(s.sort_values())

a    8
b    6
c    6
d    8
e    2
f    5
g    9
h    5
i    1
Name: 数据标签, dtype: int64
i    1
e    2
f    5
h    5
b    6
c    6
d    8
a    8
g    9
Name: 数据标签, dtype: int64


In [110]:
# 值替换
print(s)
s = pd.Series([6,2,5,1,5,6,8,8,9], index=['b', 'e', 'f', 'i', 'h', 'c', 'd', 'a', 'g'], name='数据标签')
# 把s中值为1,2的元素替换为666
# 注意：replace 是 按“值”替换，不是按位置
print(s.replace([1,2], 666))
# 映射式替换
print(s.replace({1: 888, 5:555}))
# 多对多替换, 注意：两个数组长度必须一致
print(s.replace([1,2], [666,888]))

b    6
e    2
f    5
i    1
h    5
c    6
d    8
a    8
g    9
Name: 数据标签, dtype: int64
b      6
e    666
f      5
i    666
h      5
c      6
d      8
a      8
g      9
Name: 数据标签, dtype: int64
b      6
e      2
f    555
i    888
h    555
c      6
d      8
a      8
g      9
Name: 数据标签, dtype: int64
b      6
e    888
f      5
i    666
h      5
c      6
d      8
a      8
g      9
Name: 数据标签, dtype: int64


In [112]:
# 返回series的索引对象
print(s.keys())
print(s.keys()[1])
print(s.index)
print(s.index[1])

Index(['b', 'e', 'f', 'i', 'h', 'c', 'd', 'a', 'g'], dtype='object')
e
Index(['b', 'e', 'f', 'i', 'h', 'c', 'd', 'a', 'g'], dtype='object')
e


In [111]:
s.head()

b    6
e    2
f    5
i    1
h    5
Name: 数据标签, dtype: int64

In [124]:


# 10名学生成绩
import numpy as np
np.random.seed(666)
arr = np.random.randint(50,101, 10)
s = pd.Series(arr, index=[f"学生{i+1}成绩" for i in range(len(arr))])
print(arr)
print(s)

print(s.mean())
print(s.max())
print(s.min())
# 高于平均分的学生人数
print(s[s > s.mean()])
print(s[s > s.mean()].size)
print(len(s[s > s.mean()]))
print(s[s > s.mean()].count())
pass

[94 52 95 80 56 59 80 86 77 80]
学生1成绩     94
学生2成绩     52
学生3成绩     95
学生4成绩     80
学生5成绩     56
学生6成绩     59
学生7成绩     80
学生8成绩     86
学生9成绩     77
学生10成绩    80
dtype: int32
75.9
95
52
学生1成绩     94
学生3成绩     95
学生4成绩     80
学生7成绩     80
学生8成绩     86
学生9成绩     77
学生10成绩    80
dtype: int32
7
7
7


In [160]:

# 某城市一周中每天的最高温度如下
temp = pd.Series([28,31,29,32,30,27,33], index=['周1', '周2', '周3', '周4', '周5', '周6', '周7'])
# 温度超过30的天数
print(temp[temp > 30].count())
print(temp.mean())
# 温度低到高排序
print(temp.sort_values()) # 升序
print(temp.sort_values(ascending=False)) # 降序
# 找出温度变化最大的两天
max = 0
max_index = 0
for i, v in enumerate(temp):
    if i == len(temp)-1:
        break
    # diff = temp[i+1] - v
    diff = temp.iat[i+1] - v
    if abs(diff) > max:
        max = diff
        max_index = i
print(max, max_index)
print(f"温差最大的两天是{max_index+1}和{max_index +2}, 最大温差是{max}读")
print()
# 找相邻两个数据之间的差值
print(temp.diff())
print(temp.diff().abs().sort_values(ascending=False))
print(temp.diff().abs().sort_values(ascending=False).iat[0])
print(temp.diff().abs().sort_values(ascending=False).index)
max_i = temp.diff().abs().sort_values(ascending=False).index[0]
print("标签索引：",max_i)
# 通过标签索引获取数字索引
i_index = temp.index.get_loc(max_i)
print(i_index)
print(i_index-1)
# 通过数字索引获取标签索引
print(temp.index)
print(temp.index[i_index])
# 已知「值」，获取对应的 index（可能多个）
# s[s == 5].index

3
30.0
周6    27
周1    28
周3    29
周5    30
周2    31
周4    32
周7    33
dtype: int64
周7    33
周4    32
周2    31
周5    30
周3    29
周1    28
周6    27
dtype: int64
6 5
温差最大的两天是6和7, 最大温差是6读

周1    NaN
周2    3.0
周3   -2.0
周4    3.0
周5   -2.0
周6   -3.0
周7    6.0
dtype: float64
周7    6.0
周2    3.0
周6    3.0
周4    3.0
周3    2.0
周5    2.0
周1    NaN
dtype: float64
6.0
Index(['周7', '周2', '周6', '周4', '周3', '周5', '周1'], dtype='object')
标签索引： 周7
6
5
Index(['周1', '周2', '周3', '周4', '周5', '周6', '周7'], dtype='object')
周7


66
66


In [186]:
# 某股票连续10天的收盘价
s = pd.Series([102.3,103.5,105.1,104.8,106.2,107.0,106.5,108.1,109.3,110.2], index=pd.date_range('2023-01-01',periods=10))
# print(s)
# 计算每日收益率 = 当日收盘价 / 当前日收盘价 - 1
print(s[1:s.size].values)
print(s[0:s.size-1].values)
lst = [s[1:s.size].values[i]/ s[0:s.size-1].values[i] - 1 for i in range(len(s)-1)]
lst = [np.nan] + lst
s0 = pd.Series(lst, index=pd.date_range('2023-01-01',periods=10))
print(s0)
# 找出最大，最低对应的日期
print(s0.max(), s0.idxmax(), s0.index.get_loc(s0.idxmax()))
print(s0.min(), s0.idxmin(), s0.index.get_loc(s0.idxmin()))
# 波动率
print(s0.std())

# pd内置收益率的函数
print(s.pct_change())


[103.5 105.1 104.8 106.2 107.  106.5 108.1 109.3 110.2]
[102.3 103.5 105.1 104.8 106.2 107.  106.5 108.1 109.3]
2023-01-01         NaN
2023-01-02    0.011730
2023-01-03    0.015459
2023-01-04   -0.002854
2023-01-05    0.013359
2023-01-06    0.007533
2023-01-07   -0.004673
2023-01-08    0.015023
2023-01-09    0.011101
2023-01-10    0.008234
Freq: D, dtype: float64
0.015458937198067568 2023-01-03 00:00:00 2
-0.004672897196261627 2023-01-07 00:00:00 6
0.007373623845361105
2023-01-01         NaN
2023-01-02    0.011730
2023-01-03    0.015459
2023-01-04   -0.002854
2023-01-05    0.013359
2023-01-06    0.007533
2023-01-07   -0.004673
2023-01-08    0.015023
2023-01-09    0.011101
2023-01-10    0.008234
Freq: D, dtype: float64


In [212]:

# 某产品过去12个月的销售量
# freq表示频率，M表示月,S表示每个月的开始第一天，E表示月末最后一天
s = pd.Series([120,135,145,160,155,170,180,175,190,200,210,220], index=pd.date_range('2022-01-01', periods=12, freq='MS'))
print(s)

# 计算季度平均销量, Q表示季度
# 重新采样将每3个月合并在一起
print(s.resample('QS').mean())


# 环比：这个月比上一个月增加了多少
# 同比：今年的某个月比去年的对应那个月增加了多少

# 找出连续增长超过2个月的月份
c = s.pct_change()
print(c)
b = c > 0
print(b)
# 使用滑动窗口计算连续超过两个月的
print(b.rolling(3))
print(b.rolling(3).sum())
print(b.rolling(3).sum() >= 3)
print(b[b.rolling(3).sum() >= 3])
print(b[b.rolling(3).sum() >= 3].keys())
print(b[b.rolling(3).sum() >= 3].keys().tolist())


pass

2022-01-01    120
2022-02-01    135
2022-03-01    145
2022-04-01    160
2022-05-01    155
2022-06-01    170
2022-07-01    180
2022-08-01    175
2022-09-01    190
2022-10-01    200
2022-11-01    210
2022-12-01    220
Freq: MS, dtype: int64
2022-01-01    133.333333
2022-04-01    161.666667
2022-07-01    181.666667
2022-10-01    210.000000
Freq: QS-JAN, dtype: float64
2022-01-01         NaN
2022-02-01    0.125000
2022-03-01    0.074074
2022-04-01    0.103448
2022-05-01   -0.031250
2022-06-01    0.096774
2022-07-01    0.058824
2022-08-01   -0.027778
2022-09-01    0.085714
2022-10-01    0.052632
2022-11-01    0.050000
2022-12-01    0.047619
Freq: MS, dtype: float64
2022-01-01    False
2022-02-01     True
2022-03-01     True
2022-04-01     True
2022-05-01    False
2022-06-01     True
2022-07-01     True
2022-08-01    False
2022-09-01     True
2022-10-01     True
2022-11-01     True
2022-12-01     True
Freq: MS, dtype: bool
Rolling [window=3,center=False,axis=0,method=single]
2022-01-01    Na

In [199]:
from pandas.tseries.frequencies import get_period_alias

# _offset_map 是官方内部维护的字典，包含所有官方别名
print("Pandas resample() 支持的 rule（频率别名）:")
print(get_period_alias.__dict__)

Pandas resample() 支持的 rule（频率别名）:
{}


In [249]:
import numpy as np
# 随机生成商店每小时的销售额度
np.random.seed(123)
s = pd.Series(
    np.random.randint(0, 100, 24),
    index=pd.date_range("00:00:00", periods=24, freq="h")
)
print(s)
# 按天重采样计算每天的销售额度
print(s.resample("D").sum())
# 计算每天营业时间销售额  和 非营业时间销售额 的比例
print(s[8:23])
print(s[8:23].sum())
print(s.sum() - s[8:23].sum())
print((s[8:23].sum()) / (s.sum() - s[8:23].sum()))

today_sum = s.sum()
business_data = s[(s.index.hour >= 8) & (s.index.hour <= 22)].sum()
business_data = s.between_time('08:00', '22:00').sum()
# s.between_time()
print(business_data)
not_business_data = s.sum() - business_data
not_business_data = s[(s.index.hour > 22) | (s.index.hour < 8)].sum()
print('not_business_data: ', not_business_data)
print(business_data / not_business_data)

# drop在原始数据里面去除某些数据
print(s.drop(s.between_time('08:00', '22:00').index).sum())

# 超出销售额最高的三个小时
print(s.sort_values(ascending=False))
print(s.sort_values(ascending=False)[0:3])
print(s.sort_values(ascending=False)[0:3].index)

print(s.nlargest(3))
print(s.nsmallest(3))
print()

2026-01-31 00:00:00    66
2026-01-31 01:00:00    92
2026-01-31 02:00:00    98
2026-01-31 03:00:00    17
2026-01-31 04:00:00    83
2026-01-31 05:00:00    57
2026-01-31 06:00:00    86
2026-01-31 07:00:00    97
2026-01-31 08:00:00    96
2026-01-31 09:00:00    47
2026-01-31 10:00:00    73
2026-01-31 11:00:00    32
2026-01-31 12:00:00    46
2026-01-31 13:00:00    96
2026-01-31 14:00:00    25
2026-01-31 15:00:00    83
2026-01-31 16:00:00    78
2026-01-31 17:00:00    36
2026-01-31 18:00:00    96
2026-01-31 19:00:00    80
2026-01-31 20:00:00    68
2026-01-31 21:00:00    49
2026-01-31 22:00:00    55
2026-01-31 23:00:00    67
Freq: h, dtype: int32
2026-01-31    1623
Freq: D, dtype: int32
2026-01-31 08:00:00    96
2026-01-31 09:00:00    47
2026-01-31 10:00:00    73
2026-01-31 11:00:00    32
2026-01-31 12:00:00    46
2026-01-31 13:00:00    96
2026-01-31 14:00:00    25
2026-01-31 15:00:00    83
2026-01-31 16:00:00    78
2026-01-31 17:00:00    36
2026-01-31 18:00:00    96
2026-01-31 19:00:00    80
2