In [2]:
import numpy as np

print(np.__version__)

2.2.5


In [3]:
arr = np.array([1, 2, 3])
print(arr)
print(arr[0])
print(arr[0].dtype)

arr2 = np.array([[1], [2], [3]])
print(np.dot(arr, arr2))

arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
print(arr3)
print(arr3.reshape(2, 6))
print(arr3.ravel())  # 将多维数组展开成一维数组
print(np.max(arr3))
print(np.max(arr3, axis=0))  # [17,18,19]
print(np.max(arr3, axis=1))  #[3,6,9,19]

arr5 = arr3.reshape(2, 6)
print(arr5)
print(np.transpose(arr5))  # 将数组维度对调，即数组翻转


[1 2 3]
1
int64
[14]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [17 18 19]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 17 18 19]]
[ 1  2  3  4  5  6  7  8  9 17 18 19]
19
[17 18 19]
[ 3  6  9 19]
[[ 1  2  3  4  5  6]
 [ 7  8  9 17 18 19]]
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 17]
 [ 5 18]
 [ 6 19]]


In [14]:
# 数组堆叠(vstack,hstack)，拼接
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[21, 22, 23], [24, 25, 26]])
print(arr1)
print(arr2)

# 水平堆叠（hstack） → 按 列 拼接（横向）
# 垂直堆叠（vstack） → 按 行 拼接（纵向）
print(np.hstack([arr1, arr2]))
print(np.vstack([arr1, arr2]))


[[1 2 3]
 [4 5 6]]
[[21 22 23]
 [24 25 26]]
[[ 1  2  3 21 22 23]
 [ 4  5  6 24 25 26]]
[[ 1  2  3]
 [ 4  5  6]
 [21 22 23]
 [24 25 26]]


In [15]:
# np.view, 浅拷贝，修改新对象就数组会被改变
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr_view = arr.view()
print(arr_view)
arr_view[0][1] = 666
print(arr)
print(arr_view)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[  1 666   3]
 [  4   5   6]]
[[  1 666   3]
 [  4   5   6]]


In [16]:
# np.copy，深拷贝
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr_copy = arr.copy()
print(arr_copy)
arr_copy[0][1] = 999
print(arr)
print(arr_copy)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[  1 999   3]
 [  4   5   6]]


In [20]:
# 广播
# 广播的条件，维度小的那一个的shape必须是：一个是1，另一个不是1的要和维度大的那个对应
# 如下小的是(1,3)，一维的是1，二维是3和大的(2,3)的3相同，这样才能广播
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
# [1, 2, 3] (1,3) ---广播--->>>  [[1, 2, 3],[1, 2, 3]] (2,3)
# [[1, 2, 3],[1, 2, 3]] + [[1, 2, 3],[4, 5, 6]]
# = [[2 4 6], [5 7 9]]
print(arr2 + arr1)

arr3 = np.array([[1, 2]])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
# ValueError: operands could not be broadcast together with shapes
# print(arr2 + arr3)

[[2 4 6]
 [5 7 9]]


In [41]:
# 高级索引
a = np.arange(12) ** 2  # the first 12 square numbers
print(a)
i = np.array([1, 1, 3, 8, 5])  # an array of indices
print(a[i])  # 取出数组a中索引数组对应的数据
print()

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print(a2[np.array(0)])  # [1 2 3]
print(a2[np.array(1)])  # [4 5 6]
print(a2[np.array([[0], [1]])])




[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
[[[1 2 3]]

 [[4 5 6]]]


In [44]:
# take方法
# ndarray.take(indices, axis=None, out=None, mode='raise')

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(np.take(arr, [0, 1]))
print(np.take(arr, [0, 1], axis=0))
print(np.take(arr, [0, 1], axis=1))
print(arr.take([0, 1], axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]
[[1 2]
 [4 5]
 [7 8]]


In [53]:
# 通过mask数组进行索引，即布尔索引
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
mask = arr % 2 == 0
print(mask)
print(arr[mask])
print(arr[~mask])

# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
# print(arr % 2 == 0 & arr > 5)
# 必须加一个括号，将两个boo数组进行与&运算
# & 表示将左右两个数组进行与运算，不能py中的and，
# py中的and，or，not只能用于标量的bool数据，不能用于矩阵，而在numpy中提供了 &，｜，～三个对应的运算符来进行与或非运算
print((arr % 2 == 0) & (arr > 5))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[1 3 5 7 9]
[[False False False]
 [False False  True]
 [False  True False]]


In [57]:
a = np.arange(12).reshape(3, 4)
b1 = np.array([False, True, True])  # first dim selection，行
b2 = np.array([True, False, True, False])  # second dim selection，列
print(a)
print(b1)
print(b2)
print(a[b1, :])
print(a[:, b2])
print(a[b1, b2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[False  True  True]
[ True False  True False]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[ 4 10]


In [66]:
import numpy.linalg as linalg

print(linalg)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.transpose())
# print(arr.iva(arrr))


<module 'numpy.linalg' from '/opt/homebrew/Caskroom/miniconda/base/envs/py311/lib/python3.11/site-packages/numpy/linalg/__init__.py'>
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


AttributeError: 'numpy.ndarray' object has no attribute 'iva'

In [73]:
# 自动推断形状
arr = np.arange(1, 13)
print(arr)
arr2 = arr.reshape(3, 4)
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[numpy-100](https://www.heywhale.com/mw/project/59f29f67c5f3f5119527a2cc)

In [75]:
import numpy as np

print(np.version)
print(np.__version__)
print(np.show_config)

<module 'numpy.version' from '/opt/homebrew/Caskroom/miniconda/base/envs/py311/lib/python3.11/site-packages/numpy/version.py'>
1.26.4
<function show at 0x103a40a40>


In [80]:

# 创建一个长度为10 的空向量
print(np.zeros(10))

# 查询数据所占空间
arr1 = np.array([0, 1, 2])
arr2 = np.array([0., 1.2, 2.3])
arr3 = np.array([True, False, True])
print(np.size(arr1))
print(np.size(arr1[0]))
print(np.size(arr2[0]))
print(np.size(arr3[0]))
print(arr1.itemsize)
print(arr1[0].itemsize)
print(arr2[0].itemsize)
print(arr3[0].itemsize)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
3
1
1
1
8
8
8
1


In [82]:
# 5. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)
np.info(np.add)

x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])
print(np.add(x1, x2))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [91]:
a = np.zeros(10)
print(a)
a[4] = 1
print(a)

a2 = np.arange(10, 20)
print(a2)

# 8. 反转一个向量(第一个元素变为最后一个)
print(a2[::-1])

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(lst)
print(lst[::1])
print(lst[::-1])
lst.reverse()
print(lst)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [108]:
print(np.arange(9).reshape(3, 3))

arr = np.array([1, 2, 0, 0, 4, 0])
print(arr)
# 找非0元素的索引位置
print(arr.nonzero())

print(np.eye(3))

print(np.random.random((3, 3, 3)))
# print(np.random.random((1,2,3)))
# print(np.random.random(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 2 0 0 4 0]
(array([0, 1, 4]),)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[[0.40844965 0.02304241 0.0223163 ]
  [0.42345992 0.97035645 0.22237207]
  [0.25884363 0.45444918 0.00837534]]

 [[0.25506432 0.86610632 0.81359607]
  [0.82819564 0.36081238 0.39548369]
  [0.82088099 0.14546539 0.38804403]]

 [[0.68082657 0.67636278 0.80696484]
  [0.15771947 0.18617281 0.76859988]
  [0.52730152 0.87871532 0.22765642]]]


In [112]:
a = np.random.random((10, 10))
print(np.max(a))
print(np.min(a))

print(np.random.random((10)).mean())

0.9951738362983048
0.0029750861745561075
0.4480302164165611


In [121]:
# 15. 创建一个二维数组，其中边界值为1，其余值为0
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
print(a)
a = np.zeros((5, 5))
rows, cols = a.shape
a[1:rows - 1, 1:cols - 1] = 1
print(a)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [126]:

# 16. 对于一个已存在的数组，如何添加一个用0填充的边界?
a = np.ones((3, 3))
print(a)
print(np.pad(a, 1))
# print(np.pad(a, 2))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# np.nan = Not a Number（不是一个数）
# np.inf = 正无穷大（infinity）
print(np.nan)
print(np.inf)
print(np.isnan(np.nan))
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3)
print(3 * 0.1)
print(0.3 == 3 * 0.1)

a = np.array([1, 2, np.nan, 4])
# 👉 普通统计函数遇到 nan 会“污染”结果
np.sum(a)  # nan
print(np.mean(a))  # nan
# 忽略 nan 的版本
np.nansum(a)  # 7.0
print(np.nanmean(a))  # 2.333...



nan
inf
True
nan
False
False
nan
0.3
0.30000000000000004
False
nan
2.3333333333333335


In [141]:

a = np.eye(5, 5)
print(a)

a2 = np.diag(1 + np.arange(4), k=-1)
print(a2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [150]:
a = np.ones((8, 8), dtype=int)
a[1::2, ::2] = 0
a[::2, 1::2] = 0
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [160]:
a = np.random.random((2, 3, 4))
print(a)
print(a.size)
# 问第16个元素的索引是什么
print(np.unravel_index(15, a.shape))


[[[0.82285135 0.24016159 0.28835831 0.23007172]
  [0.1761614  0.36306239 0.74830653 0.99967933]
  [0.13617336 0.80881096 0.88906344 0.07440263]]

 [[0.02602542 0.95733405 0.61910601 0.04696015]
  [0.79360222 0.44343464 0.51889206 0.13213633]
  [0.44248714 0.85743657 0.24776183 0.10573318]]]
24
(1, 0, 3)


In [10]:
# 对5*5的矩阵做归一化
a = np.arange(1, 26).reshape((5, 5))
print(a)
# (x - min) / (max - min))
minv = np.min(a)
maxv = np.max(a)
print(minv, maxv)
print((a - minv) / (maxv - minv))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
1 25
[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


In [12]:
# 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
a1 = np.arange(1, 16).reshape((5, 3))
a2 = np.arange(1, 7).reshape((3, 2))
print(a1)
print(a2)
# 矩阵乘法可以使用 dot 或 @
print(a1.dot(a2))
print(a1 @ a2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


In [25]:
# 25. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)¶
a = np.array([True, False, True, False, True, True, True, False, True, False, True, False])
print(a)

print(a[3:8])
print(~a[3:8])

a2 = np.arange(1, 9).reshape((1, 8))
print(a2)
print((a2 >= 3))
print((a2 < 8))
print((a2 >= 3) & (a2 < 8))
a2[(a2 >= 3) & (a2 < 8)] *= -1
print(a2)


[ True False  True False  True  True  True False  True False  True False]
[False  True  True  True False]
[ True False False False  True]
[[1 2 3 4 5 6 7 8]]
[[False False  True  True  True  True  True  True]]
[[ True  True  True  True  True  True  True False]]
[[False False  True  True  True  True  True False]]
[[ 1  2 -3 -4 -5 -6 -7  8]]


In [29]:
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

C:\Users\nhjcl\AppData\Local\Temp\ipykernel_6812\1667461466.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [31]:
# 30. 如何找到两个数组中的共同元素? (提示: np.intersect1d)
a1 = np.array([1, 2, 35, 6, 7, 8])
a2 = np.array([11, 22, 35, 63, 17, 8])
print(a1)
print(a2)

print(np.intersect1d(a1, a2))


[ 1  2 35  6  7  8]
[11 22 35 63 17  8]
[ 8 35]


In [33]:
# 33. 如何得到昨天，今天，明天的日期? (★☆☆)
# (提示: np.datetime64, np.timedelta64)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Yesterday is " + str(yesterday))
print("Today is " + str(today))
print("Tomorrow is " + str(tomorrow))


Yesterday is 2026-01-28
Today is 2026-01-29
Tomorrow is 2026-01-30


In [39]:
# 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)
# (提示: np.arange)
a = np.arange(25).reshape((5, 5))
a[1:, :] = a[0]
print(a)
Z = np.zeros((5, 5))
print(Z)
print(np.arange(5))
Z += np.arange(5)  # 广播
print(Z)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [46]:
# 38. 通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆)¶
# (提示: np.fromiter)
def fun38(num: int = 10):
    for i in range(num):
        yield np.random.randint(100)


print(list(fun38()))

a = np.fromiter(fun38(), dtype=int)
print(a)


[45, 83, 76, 10, 51, 52, 62, 44, 95, 12]
[ 1 34 13 71 30 44 25 60 61 99]


In [55]:
# 某城市一周中每天的最高气温为 [28,30,29,31,32,30,29]
# 给出平均气温，最高气温，最低气温
a = np.array([28, 30, 29, 31, 32, 30, 29])
print(np.mean(a), np.max(a), np.min(a))
# 气温超过30的天数
print(a > 30)
print(a[a > 30])
print(len(a[a > 30]))

print(np.sum(a > 30))

print(np.where(a > 30, 1, 0))
print(np.sum(np.where(a > 30, 1, 0)))

print(np.count_nonzero(a > 30))

29.857142857142858 32 28
[False False False  True  True False False]
[31 32]
2
2
[0 0 0 1 1 0 0]
2
2


In [61]:
# 5 名学生的成绩分别为 [59, 68, 78, 92, 88]
a = np.array([59, 68, 78, 92, 88])
# 标准差std，方差var
print(np.mean(a), np.median(a), np.std(a))

# 把分数转化为等级制 ，0<D<60<=C<70<=B<80<=A<=100
print(np.where(a < 60, 'D',
               np.where(a < 70, 'C',
                        np.where(a < 80, 'B', 'A'))))

77.0 78.0 12.263767773404714
['D' 'C' 'B' 'A' 'A']


In [63]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)
print(A * B)
print(A @ B)
print(np.dot(A, B))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [87]:
np.random.seed(0)
# 生成一个范围在[0,10)形状是(3,4)的随机数组
print(np.random.random((3,4)) * 10)
print(np.random.uniform(0, 10, size=(3, 4)))

a = np.random.randint(0, 10, size=(3, 4))
print(a)
# 计算每一列的最大值最小值
print(np.max(a, axis=0))
print(np.min(a, axis=0))
# 将所有为奇数的置为1
print(np.where(a % 2 == 1, -1, a))

[[5.48813504 7.15189366 6.02763376 5.44883183]
 [4.23654799 6.45894113 4.37587211 8.91773001]
 [9.63662761 3.83441519 7.91725038 5.2889492 ]]
[[5.68044561 9.25596638 0.71036058 0.871293  ]
 [0.20218397 8.32619846 7.78156751 8.70012148]
 [9.78618342 7.99158564 4.61479362 7.80529176]]
[[7 0 1 9]
 [9 0 4 7]
 [3 2 7 2]]
[9 2 7 9]
[3 0 1 2]
[[-1  0 -1 -1]
 [-1  0  4 -1]
 [-1  2 -1  2]]


In [91]:
np.random.seed(0)
a = np.random.randint(0, 20, (5,5))
print(a)
print(a[a > 10])
a[a > 10] = 0
print(a)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [97]:
a = np.array([120,135,110,125,130,140])
# argmax找最大值的索引
# argmin找最小值的索引
print(np.min(a), np.argmin(a))
print(np.max(a), np.argmax(a))


110 2
140 5


In [99]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# 水平拼接
print(np.concatenate((a, b)))
print(np.hstack((a,b)))
# 垂直拼接
print(np.vstack((a,b)))

pass

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [106]:
a = np.array([2,1,2,3,1,4,3])
print(a)
print(np.unique_counts(a))
print(np.unique_values(a))
print(np.unique(a, return_counts=True))

[2 1 2 3 1 4 3]
UniqueCountsResult(values=array([1, 2, 3, 4]), counts=array([2, 2, 2, 1]))
[1 2 3 4]
(array([1, 2, 3, 4]), array([2, 2, 2, 1]))
