In [1]:
# 1）低方差过滤法
# 对于特征的选择，可以直接基于方差来判断，这是最简单的。低方差的特征意味着该特征的所有样本值几乎相同，对预测影响极小，可以将其去掉。


In [2]:
import numpy as np

In [2]:
# 特征选择方法
# 低方差过滤

a = np.random.randn(100)  # 随机生成100个数据，a作为特征1

b = np.random.normal(5, 0.1, 100)  # 随机生成100个方差为0.01的数据，作为特征2

c = np.random.normal(5, 0.005, 100)  # 随机生成100个方差为0.01的数据，作为特征2

print(a.shape, b.shape, c.shape)

# 将a,b,c三个特征作为所有特征，进行特征组合
# np.vstack(a,b,c).shape=(3,100)这个不符合100个样本点3个特征的数据要求，因此对齐进行转置,
# 即可得到符合要求的特征数据X.shape=(100,3)
X = np.vstack((a,b,c)).T
print(X, X.shape)

# 经过这样处理之后，X就有100个样本每个样本有3个特征，其中第三个特征的方差小于0.01，因此在下面的特征方差过滤中会被移除掉，只保留前面两个特征。这个就是本次要演示的特征过滤方法。
# 此外，方差越小说明特征之间的差别就越小，也就是说每一个特征都差不多，即这个特征用来决定标签的作用也就不大了，所以可以移除。


# 特征数据准备好了

(100,) (100,) (100,)
[[ 8.97174193e-01  5.05980169e+00  4.99751215e+00]
 [-6.83298877e-01  4.89623833e+00  4.99174575e+00]
 [-1.34402691e+00  4.84807289e+00  5.00087326e+00]
 [-2.80049902e-01  5.18622552e+00  4.98720457e+00]
 [ 1.60212612e+00  5.02714905e+00  5.00568990e+00]
 [-1.54831456e+00  5.22225637e+00  4.99866660e+00]
 [-7.14075648e-01  5.20494129e+00  5.00049839e+00]
 [ 1.00090157e+00  5.14870058e+00  5.00287601e+00]
 [-3.70434510e-01  5.00149031e+00  5.00705485e+00]
 [ 1.28973428e+00  5.09643178e+00  5.00298395e+00]
 [ 1.18814660e+00  5.22323232e+00  4.99971583e+00]
 [-9.60353725e-01  5.01030225e+00  5.00311831e+00]
 [ 2.71120918e-02  5.04851567e+00  4.99823524e+00]
 [ 3.14138080e-01  4.82554623e+00  5.00797274e+00]
 [-2.34349326e-02  4.91305964e+00  5.00203340e+00]
 [-4.64321510e-01  5.15569976e+00  5.00644645e+00]
 [-1.87295882e+00  4.91298812e+00  4.99974488e+00]
 [-9.82064159e-02  5.01991769e+00  4.99988715e+00]
 [-1.31312471e-01  5.30203789e+00  5.00374427e+00]
 [ 7.14782

In [3]:
# 现在使用form sklearn.feature_selection import VarianceThreshold进行特征方差过滤
from sklearn.feature_selection import VarianceThreshold

vt = VarianceThreshold(threshold=0.01)
x_transfored = vt.fit_transform(X)

print(x_transfored, x_transfored.shape)
# 输出 (100, 2)，那么也就是说方差小雨0.01的c特征已经被过滤了

[[ 8.97174193e-01  5.05980169e+00]
 [-6.83298877e-01  4.89623833e+00]
 [-1.34402691e+00  4.84807289e+00]
 [-2.80049902e-01  5.18622552e+00]
 [ 1.60212612e+00  5.02714905e+00]
 [-1.54831456e+00  5.22225637e+00]
 [-7.14075648e-01  5.20494129e+00]
 [ 1.00090157e+00  5.14870058e+00]
 [-3.70434510e-01  5.00149031e+00]
 [ 1.28973428e+00  5.09643178e+00]
 [ 1.18814660e+00  5.22323232e+00]
 [-9.60353725e-01  5.01030225e+00]
 [ 2.71120918e-02  5.04851567e+00]
 [ 3.14138080e-01  4.82554623e+00]
 [-2.34349326e-02  4.91305964e+00]
 [-4.64321510e-01  5.15569976e+00]
 [-1.87295882e+00  4.91298812e+00]
 [-9.82064159e-02  5.01991769e+00]
 [-1.31312471e-01  5.30203789e+00]
 [ 7.14782396e-01  4.94153401e+00]
 [ 4.61891587e-01  4.92270151e+00]
 [ 1.74055218e+00  5.00101568e+00]
 [ 6.12011606e-02  4.83596079e+00]
 [ 3.82668111e-01  4.99324557e+00]
 [-4.19864829e-01  5.05234923e+00]
 [-1.21120430e+00  5.02128371e+00]
 [ 5.17758913e-01  5.09810469e+00]
 [-2.05259246e-01  4.91652288e+00]
 [ 6.15058642e-01  5